model: Qwen/Qwen2.5-Math-1.5B
num_rollouts: 4
batch_size: 1
max_new_tokens: 1024
data_path: open-r1/DAPO-Math-17k-Processed
output_dir: /home/ssj/Critical-Token/results
use_wandb: false
max_samples: 250
project_name: 'critical_token'
wandb_api_key: 'cd978dfe2e8a1b04f8b8cec52d3409478042cc62'
