model: Qwen/Qwen2-Math-1.5B
prompt_chunk_size: 64
max_new_tokens: 1024
temperature: 0.7
max_logprobs: 32768
top_k: 20
data_path: /home/work/minjaeoh/critical_token/dataset/hendrycks_math_solutions.json
output_dir: /home/work/minjaeoh/critical_token/results
use_wandb: true
project_name: 'critical_token'
wandb_api_key: 'cd978dfe2e8a1b04f8b8cec52d3409478042cc62'
resume: true